sonar.projectKey=AS241S5_AEJ_29-be
sonar.organization=asumivillafuerte

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.sourceEncoding=UTF-8
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.exclusions=**/build-wrapper-dump.json
