# kubectl apply -f asumi-villafuerte-29.yml
apiVersion: v1
kind: Secret
metadata:
  name: asumi-villafuerte-29-secret
  namespace: asumi-villafuerte-29-namespace
type: Opaque
data:
  DATABASE_URL: cjJkYmM6cG9zdGdyZXNxbDovL25lb25kYl9vd25lcjpucGdfNmVYUVc1UEFEWkJIQGVwLWRlbGljYXRlLW1lYWRvdy1hbWdvd24wei1wb29sZXIuYy01LnVzLWVhc3QtMS5hd3MubmVvbi50ZWNoL25lb25kYj9zc2xtb2RlPXJlcXVpcmUmY2hhbm5lbF9iaW5kaW5nPXJlcXVpcmU=
  DATABASE_USERNAME: bmVvbmRiX293bmVy
  DATABASE_PASSWORD: bnBnXzZlWFFXNVBBRFpCSA==
  TRANSLATE_API_URL: aHR0cHM6Ly9nb29nbGUtdHJhbnNsYXRlMTEzLnAucmFwaWRhcGkuY29t
  TRANSLATE_API_HOST: Z29vZ2xlLXRyYW5zbGF0ZTExMy5wLnJhcGlkYXBpLmNvbQ==
  TRANSLATE_API_KEY: N2VlZjQyYTY4Nm1zaDU1MWVkODI4NzljNTdiM3AxY2M2M2Fqc245NmMwZGI0N2Q0NjE=
  YOUTUBE_API_URL: aHR0cHM6Ly95b3V0dWJlLW1wMzEwLnAucmFwaWRhcGkuY29t
  YOUTUBE_API_HOST: eW91dHViZS1tcDMxMC5wLnJhcGlkYXBpLmNvbQ==
  YOUTUBE_API_KEY: N2VlZjQyYTY4Nm1zaDU1MWVkODI4NzljNTdiM3AxY2M2M2Fqc245NmMwZGI0N2Q0NjE=

# Comandos para convertir a Base64 y decodificar | https://www.convertstring.com/es/EncodeDecode/Base64Encode
# echo -n "demo123" | base64
# echo "ZGVtbzEyMw==" | base64 --decode